### ISSUE TITLE
example log level

### ISSUE THREAD

**Issue by jschoch** [esp32m/logging#5]
It may not be obvious to a new user that log_i is filtered by default.  Suggest changing it to log_e so it works with the default settings.

**Comment by dyarkovoy** [comment]
It should not be filtered. The default log level is LogLevel::Debug:
https://github.com/esp32m/logging/blob/6295ce3cf832544829c4427a0702fdf0ff613c82/src/logging.cpp#L17
so all messages except LogLevel::Verbose should pass through

**Comment by jschoch** [comment]
in platformio you have to set a lower log level as a build flag I believe.

**Comment by dyarkovoy** [comment]
Maybe, but this library doesn't use any PlatformIO flags or settings

**Comment by jschoch** [comment]
well, it didn't  work when I tried to use it and I had to do a simplified test project after I remembered that there was a debug build flag.  Up to you but it may help some platformio users.

**Comment by dyarkovoy** [comment]
Can you share your simplifie test project so I can understand how it di not work?

**Comment by jschoch** [comment]
I used the exact example in the readme.  it workw if you change log_i to  log_e.  alternatively you could simply point out in the readme that platform.io requires a build flag to configure the log level in the readme.

**Comment by dyarkovoy** [comment]
Okay I checked the example and I see what you mean. The problem lies in the `log_x` macro. If you use the example as is, the `log_x` macro calls Arduino logging libs, and indeed, in this case log level set in PlatformIO matters. But it is possible to bypass Arduino and log directly to appenders simply by adding the 
```
build_flags =
    -DLOGGING_REDEFINE_LOG_X
```
to the platformio.ini.
I added this info to the readme. Thank you for noticing.
